In [2]:
import pandas as pd

In [3]:
ventas_ancho = {
    'Producto': ['Laptop', 'Mouse'],
    'Enero': [1000, 20],
    'Febrero': [1100, 25]
}
ventas_ancho

{'Producto': ['Laptop', 'Mouse'], 'Enero': [1000, 20], 'Febrero': [1100, 25]}

In [4]:
ventas_ancho_df = pd.DataFrame(ventas_ancho)
ventas_ancho_df
#

  Producto  Enero  Febrero
0   Laptop   1000     1100
1    Mouse     20       25

In [5]:
ventas_ancho_df.describe()

             Enero     Febrero
count     2.000000     2.00000
mean    510.000000   562.50000
std     692.964646   760.13979
min      20.000000    25.00000
25%     265.000000   293.75000
50%     510.000000   562.50000
75%     755.000000   831.25000
max    1000.000000  1100.00000

In [6]:
ventas_ancho_df.info()
#

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Producto  2 non-null      object
 1   Enero     2 non-null      int64
 2   Febrero   2 non-null      int64
dtypes: int64(2), object(1)
memory usage: 180.0+ bytes

In [7]:
ventas_ancho_df.head()

  Producto  Enero  Febrero
0   Laptop   1000     1100
1    Mouse     20       25

In [8]:
ventas_ancho_df.tail()
#

  Producto  Enero  Febrero
0   Laptop   1000     1100
1    Mouse     20       25

In [9]:
ventas_ancho_df.columns

Index(['Producto', 'Enero', 'Febrero'], dtype='object')

In [10]:
ventas_ancho_df.index
#

RangeIndex(start=0, stop=2, step=1)

In [11]:
ventas_ancho_df.drop_duplicates()

  Producto  Enero  Febrero
0   Laptop   1000     1100
1    Mouse     20       25

In [12]:
ventas_ancho_df.Enero

0    1000
1      20
Name: Enero, dtype: int64

In [13]:
ventas_ancho_df.keys()

Index(['Producto', 'Enero', 'Febrero'], dtype='object')

In [14]:
ventas_ancho_df.values
#

array([['Laptop', 1000, 1100],
       ['Mouse', 20, 25]], dtype=object)

Transformación: Usa pandas para pasar estos datos a formato "largo" (que la columna 'Mes' sea variable y 'Ventas' sea el valor).

In [15]:
ventas_largo_df = ventas_ancho_df.melt(id_vars='Producto', var_name='Mes', value_name='Ventas')
ventas_largo_df

  Producto      Mes  Ventas
0   Laptop    Enero    1000
1    Mouse    Enero      20
2   Laptop  Febrero    1100
3    Mouse  Febrero      25

In [16]:
ventas_largo_df.Ventas

0    1000
1      20
2    1100
3      25
Name: Ventas, dtype: int64

Limpieza/Cálculo: Aplica un descuento del 10% a todos los valores de ventas usando Dictionary Comprehension sobre los valores numéricos.

In [17]:

ventas_largo_df.Ventas = ventas_largo_df.Ventas.apply(lambda x: x * 0.9)
ventas_largo_df
#

  Producto      Mes  Ventas
0   Laptop    Enero   900.0
1    Mouse    Enero    18.0
2   Laptop  Febrero   990.0
3    Mouse  Febrero    22.5

In [18]:
ventas_largo_df.Ventas

0    900.0
1     18.0
2    990.0
3     22.5
Name: Ventas, dtype: float64

transformación (de largo a ancho)

In [24]:
# 1. Realizamos el pivot
ventas_ancho_preparado_df = ventas_largo_df.pivot_table(index='Producto',
                                           columns='Mes',
                                           values='Ventas',
                                           aggfunc='sum') # Suma los valores si hay duplicados

# 2. El paso clave: resetear el índice para que 'Producto' vuelva a ser una columna
ventas_ancho_preparado_df = ventas_ancho_preparado_df.reset_index()

# 3. (Opcional) Limpiar el nombre de la columna de ejes si aparece como 'Mes'
ventas_ancho_preparado_df.columns.name = None

ventas_ancho_preparado_df

  Producto  Enero  Febrero
0   Laptop  900.0    990.0
1    Mouse   18.0     22.5